### ISSUE TITLE
Add Carthage support?

### ISSUE THREAD

**Issue by opfeffer** [rdignard08/RGLockbox#5]
Can you add support for Carthage dependency manager in addition to Cocoapods?

Currently, your included `Cartfile` references RGLockbox itself and throws `carthage update` into an infinite loop!

**Comment by rdignard08** [comment]
fixed, that was just for testing that the carthage targets were building correctly.  Sorry about that!

**Comment by rdignard08** [comment]
You should target `swift-master` for now

Edit: tag 2.2.1 is available with this fix
