### ISSUE TITLE
Disable Logs

### ISSUE THREAD

**Issue by dehlen** [rdignard08/RGLockbox#6]
I'd love to have an option to disable logs written by this library. In some case I want to test something and the logs generated by RGLockbox pollute my debug console. Any plans to add a property `enableLogs` or something like that to disable log messages ?

Cheers,
David

**Comment by rdignard08** [comment]
Have you tried `rg_set_logging_severity(.None)` ?  Or do you want something at compile time?  I added it a week ago so you may have to upgrade

**Comment by rdignard08** [comment]
Also in the latest version it shouldn't log at all unless you set the log level to `.Trace`

**Comment by dehlen** [comment]
Thanks for your comments. Since you provided the possibility to solve this issue I'll mark this one as closed.
