### ISSUE TITLE
swift-3 branch choking on enabled bitcode when archiving

### ISSUE THREAD

**Issue by opfeffer** [rdignard08/RGLockbox#7]
When trying to pull in `swift-3` branch via carthage, `carthage build` fails. Manually opening the codebase and disabling bitcode seems to fix the problem.

I know `swift-3` branch is still under active development, figured I'd let you know though!

Thanks for the great work

**Comment by rdignard08** [comment]
Thanks! I can't quite get to the bottom of this with Xcode in its current state.  I've disabled bitcode for now so other people aren't blocked

**Comment by rdignard08** [comment]
I believe I have it working now

**Comment by rdignard08** [comment]
closing as it appears to be resolved

**Comment by opfeffer** [comment]
Sorry I hadnt been able to get back to this for a couple of days -- just ran `carthage update` with your `swift-master` branch and it works like a charm. Thanks for looking into&fix. Great framework.
